/**
 * Alert Notification Email Template
 * Generates HTML email for system alerts and monitoring notifications
 */

interface Alert {
  severity: string;
  name: string;
  startsAt: Date;
  annotations: {
    summary?: string;
    description?: string;
    runbook_url?: string;
  };
  labels: Record<string, string>;
}

/**
 * Get severity color for alert level
 */
function getSeverityColor(severity: string): string {
  switch (severity.toLowerCase()) {
    case 'critical':
      return '#dc3545';
    case 'high':
      return '#fd7e14';
    case 'medium':
      return '#ffc107';
    case 'low':
      return '#17a2b8';
    default:
      return '#6c757d';
  }
}

/**
 * Generate alert notification email HTML
 */
export function generateAlertEmail(alert: Alert): string {
  return `
<html>
  <body style="font-family: Arial, sans-serif; margin: 0; padding: 20px;">
    <div style="max-width: 600px; margin: 0 auto;">
      <div style="background-color: ${getSeverityColor(alert.severity)}; color: white; padding: 15px; border-radius: 5px 5px 0 0;">
        <h2 style="margin: 0;">[${alert.severity.toUpperCase()}] Alert</h2>
      </div>
      <div style="border: 1px solid #ddd; border-top: none; padding: 20px; border-radius: 0 0 5px 5px;">
        <h3>${alert.annotations.summary || alert.name}</h3>
        <p><strong>Description:</strong> ${alert.annotations.description || 'No description provided'}</p>
        <p><strong>Severity:</strong> ${alert.severity.toUpperCase()}</p>
        <p><strong>Team:</strong> ${alert.labels.team || 'Unknown'}</p>
        <p><strong>Started At:</strong> ${alert.startsAt.toISOString()}</p>
        ${alert.annotations.runbook_url ? `<p><strong>Runbook:</strong> <a href="${alert.annotations.runbook_url}">View Runbook</a></p>` : ''}
        
        <h4>Labels:</h4>
        <ul>
          ${Object.entries(alert.labels).map(([key, value]) => `<li><strong>${key}:</strong> ${value}</li>`).join('')}
        </ul>
        
        <div style="margin-top: 20px; padding: 10px; background-color: #f5f5f5; border-radius: 3px;">
          <small>This alert was generated by TripleCheck Monitoring System</small>
        </div>
      </div>
    </div>
  </body>
</html>`;
}
