"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotFound = exports.Blog = exports.PressMedia = exports.Partners = exports.OurStory = exports.Resources = exports.Pricing = exports.Features = exports.Home = void 0;
// Barrel exports for shared pages
var Home_1 = require("./Home");
Object.defineProperty(exports, "Home", { enumerable: true, get: function () { return Home_1.default; } });
var Features_1 = require("./Features");
Object.defineProperty(exports, "Features", { enumerable: true, get: function () { return Features_1.default; } });
var Pricing_1 = require("./Pricing");
Object.defineProperty(exports, "Pricing", { enumerable: true, get: function () { return Pricing_1.default; } });
var Resources_1 = require("./Resources");
Object.defineProperty(exports, "Resources", { enumerable: true, get: function () { return Resources_1.default; } });
var OurStory_1 = require("./OurStory");
Object.defineProperty(exports, "OurStory", { enumerable: true, get: function () { return OurStory_1.default; } });
var Partners_1 = require("./Partners");
Object.defineProperty(exports, "Partners", { enumerable: true, get: function () { return Partners_1.default; } });
var PressMedia_1 = require("./PressMedia");
Object.defineProperty(exports, "PressMedia", { enumerable: true, get: function () { return PressMedia_1.default; } });
var Blog_1 = require("./Blog");
Object.defineProperty(exports, "Blog", { enumerable: true, get: function () { return Blog_1.default; } });
var NotFound_1 = require("./NotFound");
Object.defineProperty(exports, "NotFound", { enumerable: true, get: function () { return NotFound_1.default; } });
