"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCode = void 0;
/**
 * Application-specific error codes
 */
var ErrorCode;
(function (ErrorCode) {
    // Authentication & Authorization
    ErrorCode["INVALID_CREDENTIALS"] = "INVALID_CREDENTIALS";
    ErrorCode["TOKEN_EXPIRED"] = "TOKEN_EXPIRED";
    ErrorCode["TOKEN_INVALID"] = "TOKEN_INVALID";
    ErrorCode["SESSION_EXPIRED"] = "SESSION_EXPIRED";
    ErrorCode["INSUFFICIENT_PERMISSIONS"] = "INSUFFICIENT_PERMISSIONS";
    ErrorCode["USERNAME_EXISTS"] = "USERNAME_EXISTS";
    ErrorCode["REGISTRATION_FAILED"] = "REGISTRATION_FAILED";
    ErrorCode["LOGIN_FAILED"] = "LOGIN_FAILED";
    ErrorCode["LOGOUT_FAILED"] = "LOGOUT_FAILED";
    ErrorCode["AUTH_REQUIRED"] = "AUTH_REQUIRED";
    ErrorCode["RATE_LIMITED"] = "RATE_LIMITED";
    ErrorCode["USER_NOT_FOUND"] = "USER_NOT_FOUND";
    ErrorCode["INVALID_SESSION"] = "INVALID_SESSION";
    ErrorCode["SESSION_CREATION_FAILED"] = "SESSION_CREATION_FAILED";
    ErrorCode["PASSWORD_RESET_REQUIRED"] = "PASSWORD_RESET_REQUIRED";
    ErrorCode["ACCOUNT_LOCKED"] = "ACCOUNT_LOCKED";
    ErrorCode["TOKEN_REQUIRED"] = "TOKEN_REQUIRED";
    // Validation
    ErrorCode["VALIDATION_FAILED"] = "VALIDATION_FAILED";
    ErrorCode["REQUIRED_FIELD_MISSING"] = "REQUIRED_FIELD_MISSING";
    ErrorCode["INVALID_FORMAT"] = "INVALID_FORMAT";
    ErrorCode["INVALID_EMAIL"] = "INVALID_EMAIL";
    ErrorCode["INVALID_USERNAME"] = "INVALID_USERNAME";
    ErrorCode["USERNAME_TOO_SHORT"] = "USERNAME_TOO_SHORT";
    ErrorCode["USERNAME_TOO_LONG"] = "USERNAME_TOO_LONG";
    ErrorCode["PASSWORD_TOO_SHORT"] = "PASSWORD_TOO_SHORT";
    ErrorCode["PASSWORD_TOO_LONG"] = "PASSWORD_TOO_LONG";
    ErrorCode["PASSWORD_WEAK"] = "PASSWORD_WEAK";
    ErrorCode["INVALID_PROPERTY_ID"] = "INVALID_PROPERTY_ID";
    ErrorCode["INVALID_USER_ID"] = "INVALID_USER_ID";
    ErrorCode["INVALID_REVIEW_ID"] = "INVALID_REVIEW_ID";
    // Database
    ErrorCode["DATABASE_CONNECTION_FAILED"] = "DATABASE_CONNECTION_FAILED";
    ErrorCode["DATABASE_ERROR"] = "DATABASE_ERROR";
    ErrorCode["CONNECTION_FAILED"] = "CONNECTION_FAILED";
    ErrorCode["TRANSACTION_FAILED"] = "TRANSACTION_FAILED";
    ErrorCode["DUPLICATE_RECORD"] = "DUPLICATE_RECORD";
    ErrorCode["DUPLICATE_ENTRY"] = "DUPLICATE_ENTRY";
    ErrorCode["CONSTRAINT_VIOLATION"] = "CONSTRAINT_VIOLATION";
    ErrorCode["FOREIGN_KEY_VIOLATION"] = "FOREIGN_KEY_VIOLATION";
    ErrorCode["NOT_NULL_VIOLATION"] = "NOT_NULL_VIOLATION";
    ErrorCode["RECORD_NOT_FOUND"] = "RECORD_NOT_FOUND";
    ErrorCode["UPDATE_FAILED"] = "UPDATE_FAILED";
    ErrorCode["DELETE_FAILED"] = "DELETE_FAILED";
    ErrorCode["INSERT_FAILED"] = "INSERT_FAILED";
    // Business Logic & Domain
    ErrorCode["NOT_FOUND"] = "NOT_FOUND";
    ErrorCode["RESOURCE_CONFLICT"] = "RESOURCE_CONFLICT";
    ErrorCode["RATE_LIMIT_EXCEEDED"] = "RATE_LIMIT_EXCEEDED";
    // Property Management
    ErrorCode["PROPERTY_NOT_FOUND"] = "PROPERTY_NOT_FOUND";
    ErrorCode["PROPERTY_CREATION_FAILED"] = "PROPERTY_CREATION_FAILED";
    ErrorCode["PROPERTY_UPDATE_FAILED"] = "PROPERTY_UPDATE_FAILED";
    ErrorCode["PROPERTY_DELETE_FAILED"] = "PROPERTY_DELETE_FAILED";
    ErrorCode["PROPERTY_SEARCH_FAILED"] = "PROPERTY_SEARCH_FAILED";
    ErrorCode["INVALID_PROPERTY_DATA"] = "INVALID_PROPERTY_DATA";
    ErrorCode["PROPERTY_ALREADY_EXISTS"] = "PROPERTY_ALREADY_EXISTS";
    ErrorCode["PROPERTY_NOT_OWNED"] = "PROPERTY_NOT_OWNED";
    ErrorCode["VERIFICATION_FAILED"] = "VERIFICATION_FAILED";
    ErrorCode["VERIFICATION_PENDING"] = "VERIFICATION_PENDING";
    // User Management
    ErrorCode["USER_CREATION_FAILED"] = "USER_CREATION_FAILED";
    ErrorCode["USER_UPDATE_FAILED"] = "USER_UPDATE_FAILED";
    ErrorCode["USER_DELETE_FAILED"] = "USER_DELETE_FAILED";
    ErrorCode["PROFILE_UPDATE_FAILED"] = "PROFILE_UPDATE_FAILED";
    ErrorCode["TRUST_SCORE_UPDATE_FAILED"] = "TRUST_SCORE_UPDATE_FAILED";
    ErrorCode["AGENT_VERIFICATION_FAILED"] = "AGENT_VERIFICATION_FAILED";
    ErrorCode["INSUFFICIENT_TRUST_SCORE"] = "INSUFFICIENT_TRUST_SCORE";
    // Review System
    ErrorCode["REVIEW_NOT_FOUND"] = "REVIEW_NOT_FOUND";
    ErrorCode["REVIEW_CREATION_FAILED"] = "REVIEW_CREATION_FAILED";
    ErrorCode["REVIEW_UPDATE_FAILED"] = "REVIEW_UPDATE_FAILED";
    ErrorCode["REVIEW_DELETE_FAILED"] = "REVIEW_DELETE_FAILED";
    ErrorCode["DUPLICATE_REVIEW"] = "DUPLICATE_REVIEW";
    ErrorCode["CANNOT_REVIEW_OWN_PROPERTY"] = "CANNOT_REVIEW_OWN_PROPERTY";
    ErrorCode["REVIEW_NOT_OWNED"] = "REVIEW_NOT_OWNED";
    // File Operations
    ErrorCode["FILE_UPLOAD_FAILED"] = "FILE_UPLOAD_FAILED";
    ErrorCode["FILE_TOO_LARGE"] = "FILE_TOO_LARGE";
    ErrorCode["INVALID_FILE_TYPE"] = "INVALID_FILE_TYPE";
    ErrorCode["FILE_NOT_FOUND"] = "FILE_NOT_FOUND";
    ErrorCode["FILE_PROCESSING_FAILED"] = "FILE_PROCESSING_FAILED";
    ErrorCode["UPLOAD_DIRECTORY_ERROR"] = "UPLOAD_DIRECTORY_ERROR";
    // AI & Machine Learning
    ErrorCode["AI_VERIFICATION_FAILED"] = "AI_VERIFICATION_FAILED";
    ErrorCode["FRAUD_DETECTION_FAILED"] = "FRAUD_DETECTION_FAILED";
    ErrorCode["AI_SERVICE_UNAVAILABLE"] = "AI_SERVICE_UNAVAILABLE";
    ErrorCode["VERIFICATION_TIMEOUT"] = "VERIFICATION_TIMEOUT";
    ErrorCode["INSUFFICIENT_DATA"] = "INSUFFICIENT_DATA";
    ErrorCode["AI_MODEL_ERROR"] = "AI_MODEL_ERROR";
    // Search Operations
    ErrorCode["SEARCH_QUERY_REQUIRED"] = "SEARCH_QUERY_REQUIRED";
    ErrorCode["SEARCH_FAILED"] = "SEARCH_FAILED";
    ErrorCode["INVALID_SEARCH_FILTERS"] = "INVALID_SEARCH_FILTERS";
    ErrorCode["LOCATION_SEARCH_FAILED"] = "LOCATION_SEARCH_FAILED";
    ErrorCode["SEARCH_TIMEOUT"] = "SEARCH_TIMEOUT";
    ErrorCode["TOO_MANY_RESULTS"] = "TOO_MANY_RESULTS";
    // External Services
    ErrorCode["EXTERNAL_SERVICE_ERROR"] = "EXTERNAL_SERVICE_ERROR";
    ErrorCode["TIMEOUT"] = "TIMEOUT";
    // System & Configuration
    ErrorCode["INTERNAL_SERVER_ERROR"] = "INTERNAL_SERVER_ERROR";
    ErrorCode["CONFIGURATION_ERROR"] = "CONFIGURATION_ERROR";
    ErrorCode["SERVICE_UNAVAILABLE"] = "SERVICE_UNAVAILABLE";
    ErrorCode["REQUEST_TIMEOUT"] = "REQUEST_TIMEOUT";
    ErrorCode["INVALID_REQUEST"] = "INVALID_REQUEST";
    ErrorCode["MALFORMED_DATA"] = "MALFORMED_DATA";
    ErrorCode["OPERATION_FAILED"] = "OPERATION_FAILED";
    ErrorCode["UNKNOWN_ERROR"] = "UNKNOWN_ERROR";
    // Client-side
    ErrorCode["CLIENT_RUNTIME_ERROR"] = "CLIENT_RUNTIME_ERROR";
})(ErrorCode || (exports.ErrorCode = ErrorCode = {}));
