// src/shared/error-handling/constants/error-categories.ts
export enum ErrorCategory {
    VALIDATION = 'VALIDATION',
    AUTHENTICATION = 'AUTHENTICATION',
    AUTHORIZATION = 'AUTHORIZATION',
    NOT_FOUND = 'NOT_FOUND',
    CONFLICT = 'CONFLICT',
    RATE_LIMIT = 'RATE_LIMIT',
    EXTERNAL_SERVICE = 'EXTERNAL_SERVICE',
    DATABASE = 'DATABASE',
    BUSINESS_LOGIC = 'BUSINESS_LOGIC',
    SYSTEM = 'SYSTEM',
    SECURITY = 'SECURITY',
    NETWORK = 'NETWORK',
    PERFORMANCE = 'PERFORMANCE',
    CONFIGURATION = 'CONFIGURATION',
  }