/**
 * Application-specific error codes
 */
export enum ErrorCode {
    // Authentication & Authorization
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    SESSION_EXPIRED = 'SESSION_EXPIRED',
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
    USERNAME_EXISTS = 'USERNAME_EXISTS',
    REGISTRATION_FAILED = 'REGISTRATION_FAILED',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT_FAILED = 'LOGOUT_FAILED',
    AUTH_REQUIRED = 'AUTH_REQUIRED',
    RATE_LIMITED = 'RATE_LIMITED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_SESSION = 'INVALID_SESSION',
    SESSION_CREATION_FAILED = 'SESSION_CREATION_FAILED',
    PASSWORD_RESET_REQUIRED = 'PASSWORD_RESET_REQUIRED',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    TOKEN_REQUIRED = 'TOKEN_REQUIRED',
    
    // Validation
    VALIDATION_FAILED = 'VALIDATION_FAILED',
    REQUIRED_FIELD_MISSING = 'REQUIRED_FIELD_MISSING',
    INVALID_FORMAT = 'INVALID_FORMAT',
    INVALID_EMAIL = 'INVALID_EMAIL',
    INVALID_USERNAME = 'INVALID_USERNAME',
    USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT',
    USERNAME_TOO_LONG = 'USERNAME_TOO_LONG',
    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
    PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
    PASSWORD_WEAK = 'PASSWORD_WEAK',
    INVALID_PROPERTY_ID = 'INVALID_PROPERTY_ID',
    INVALID_USER_ID = 'INVALID_USER_ID',
    INVALID_REVIEW_ID = 'INVALID_REVIEW_ID',
    
    // Database
    DATABASE_CONNECTION_FAILED = 'DATABASE_CONNECTION_FAILED',
    DATABASE_ERROR = 'DATABASE_ERROR',
    CONNECTION_FAILED = 'CONNECTION_FAILED',
    TRANSACTION_FAILED = 'TRANSACTION_FAILED',
    DUPLICATE_RECORD = 'DUPLICATE_RECORD',
    DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
    CONSTRAINT_VIOLATION = 'CONSTRAINT_VIOLATION',
    FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',
    NOT_NULL_VIOLATION = 'NOT_NULL_VIOLATION',
    RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
    UPDATE_FAILED = 'UPDATE_FAILED',
    DELETE_FAILED = 'DELETE_FAILED',
    INSERT_FAILED = 'INSERT_FAILED',
    
    // Business Logic & Domain
    NOT_FOUND = 'NOT_FOUND',
    RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    
    // Property Management
    PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND',
    PROPERTY_CREATION_FAILED = 'PROPERTY_CREATION_FAILED',
    PROPERTY_UPDATE_FAILED = 'PROPERTY_UPDATE_FAILED',
    PROPERTY_DELETE_FAILED = 'PROPERTY_DELETE_FAILED',
    PROPERTY_SEARCH_FAILED = 'PROPERTY_SEARCH_FAILED',
    INVALID_PROPERTY_DATA = 'INVALID_PROPERTY_DATA',
    PROPERTY_ALREADY_EXISTS = 'PROPERTY_ALREADY_EXISTS',
    PROPERTY_NOT_OWNED = 'PROPERTY_NOT_OWNED',
    VERIFICATION_FAILED = 'VERIFICATION_FAILED',
    VERIFICATION_PENDING = 'VERIFICATION_PENDING',
    
    // User Management
    USER_CREATION_FAILED = 'USER_CREATION_FAILED',
    USER_UPDATE_FAILED = 'USER_UPDATE_FAILED',
    USER_DELETE_FAILED = 'USER_DELETE_FAILED',
    PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED',
    TRUST_SCORE_UPDATE_FAILED = 'TRUST_SCORE_UPDATE_FAILED',
    AGENT_VERIFICATION_FAILED = 'AGENT_VERIFICATION_FAILED',
    INSUFFICIENT_TRUST_SCORE = 'INSUFFICIENT_TRUST_SCORE',
    
    // Review System
    REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
    REVIEW_CREATION_FAILED = 'REVIEW_CREATION_FAILED',
    REVIEW_UPDATE_FAILED = 'REVIEW_UPDATE_FAILED',
    REVIEW_DELETE_FAILED = 'REVIEW_DELETE_FAILED',
    DUPLICATE_REVIEW = 'DUPLICATE_REVIEW',
    CANNOT_REVIEW_OWN_PROPERTY = 'CANNOT_REVIEW_OWN_PROPERTY',
    REVIEW_NOT_OWNED = 'REVIEW_NOT_OWNED',
    
    // File Operations
    FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED',
    FILE_TOO_LARGE = 'FILE_TOO_LARGE',
    INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
    FILE_NOT_FOUND = 'FILE_NOT_FOUND',
    FILE_PROCESSING_FAILED = 'FILE_PROCESSING_FAILED',
    UPLOAD_DIRECTORY_ERROR = 'UPLOAD_DIRECTORY_ERROR',
    
    // AI & Machine Learning
    AI_VERIFICATION_FAILED = 'AI_VERIFICATION_FAILED',
    FRAUD_DETECTION_FAILED = 'FRAUD_DETECTION_FAILED',
    AI_SERVICE_UNAVAILABLE = 'AI_SERVICE_UNAVAILABLE',
    VERIFICATION_TIMEOUT = 'VERIFICATION_TIMEOUT',
    INSUFFICIENT_DATA = 'INSUFFICIENT_DATA',
    AI_MODEL_ERROR = 'AI_MODEL_ERROR',
    
    // Search Operations
    SEARCH_QUERY_REQUIRED = 'SEARCH_QUERY_REQUIRED',
    SEARCH_FAILED = 'SEARCH_FAILED',
    INVALID_SEARCH_FILTERS = 'INVALID_SEARCH_FILTERS',
    LOCATION_SEARCH_FAILED = 'LOCATION_SEARCH_FAILED',
    SEARCH_TIMEOUT = 'SEARCH_TIMEOUT',
    TOO_MANY_RESULTS = 'TOO_MANY_RESULTS',
    
    // External Services
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
    TIMEOUT = 'TIMEOUT',
    
    // System & Configuration
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
    INVALID_REQUEST = 'INVALID_REQUEST',
    MALFORMED_DATA = 'MALFORMED_DATA',
    OPERATION_FAILED = 'OPERATION_FAILED',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    
    // Client-side
    CLIENT_RUNTIME_ERROR = 'CLIENT_RUNTIME_ERROR',
  }